### ISSUE TITLE
Not work on Pycharm (mac os)

### ISSUE THREAD

**Issue by MolunYu** [FirstTimeInForever/intellij-music#3]
I'm so glad with your artistic and technical masterpiece, it's just what I want so far.
But it not works on Pycharm(2019.2.5) on macOS(Catalina 10.15.2).
After download and restart Pycharm, the donwloading of "Fancy music: Downloading sound font" will start, but it never finish, just keep on downloading.

Do you have any idea?

**Comment by FirstTimeInForever** [comment]
@MolunYu Hi and thank you for the interest to our plugin!
I have just tested version from marketplace with latest PyCharm Professional 2019.3.1 on Catalina 10.15.2 (Sorry, I could not test it with 2019.2.5). It was working as expected. The soundfont download took ~1 minute with my potato internet.
For consistency across all platforms we use custom midi soundfont, so the sounds stay the same on each OS. The soundfont file is about 140MB, so it may take some time to download.
You can manually download soundfont file from [this link](https://raw.githubusercontent.com/urish/cinto/master/media/FluidR3%20GM.sf2). Also, you will need to download all files from [here](https://github.com/FirstTimeInForever/intellij-music/tree/master/plugin/assets).
Then create `~/.intellij-fancy-music-plugin` directory and move all downloaded files there. Restart your IDE and everything should work.

In case of any other results, please attach your `idea.log` (in PyCharm click `Help > Show Log In Finder`).

**Comment by MolunYu** [comment]
@FirstTimeInForever  Great! It works so well, thank you!
With your plugin, my soul seems to be absorbed in the great tune following each typing of the keyboard.
Excellent!  Thank you for the great work.
